" vimrc
set encoding=utf-8
scriptencoding utf-8

set fileencodings=utf-8,cp932,euc-jp,fefault,latin
set fileformats=unix,dos,mac

" プラグインがロードされるか
function! s:load_plugin(plugin_name)
  return &loadplugins && stridx(&runtimepath, a:plugin_name) >= 0
endfunction

packloadall

helptags ALL

filetype plugin indent on
syntax enable

set nonumber
set nowrap
set list listchars=tab:>-,trail:-,nbsp:%,extends:>

set showmatch
set whichwrap=h,l
set scrolloff=3

if executable('jvgrep')
  set grepprg=jvgrep
endif

" Search
set ignorecase
set smartcase
set hlsearch

" Buffer
set hidden
set history=5000

" ステータスライン
set laststatus=2
set ruler

" バックアップ
set nobackup

" スワップ
silent! call mkdir($HOME . '/vimfiles/swap', 'p')
set directory=$HOME/vimfiles/swap
set swapfile

" UNDO
if has('persistent-undo')
  silent! call mkdir($HOME . '/vimfiles/undo', 'p')
  set undodir=$HOME/vimfiles/undo
  set undofile
endif

set background=dark
if s:load_plugin('gruvbox')
  colorscheme gruvbox
else
  colorscheme elflord
end

" インデント
set cindent
set cinoptions+=:0,j1

" incsearch.vim
if s:load_plugin('incsearch.vim') && s:load_plugin('asterisk.vim')
  map /  <Plug>(incsearch-forward)
  map ?  <Plug>(incsearch-backward)
  map g/ <Plug>(incsearch-stay)
  map *   <Plug>(incsearch-nohl)<Plug>(asterisk-*)
  map g*  <Plug>(incsearch-nohl)<Plug>(asterisk-g*)
  map #   <Plug>(incsearch-nohl)<Plug>(asterisk-#)
  map g#  <Plug>(incsearch-nohl)<Plug>(asterisk-g#)
  map z*  <Plug>(incsearch-nohl0)<Plug>(asterisk-z*)
  map gz* <Plug>(incsearch-nohl0)<Plug>(asterisk-gz*)
  map z#  <Plug>(incsearch-nohl0)<Plug>(asterisk-z#)
  map gz# <Plug>(incsearch-nohl0)<Plug>(asterisk-gz#)
endif

" FileType
augroup MyFileType
  autocmd!
  autocmd FileType java,php,html,xml,sql,python
    \ set et sw=4 ts=4 sts=4
  autocmd FileType go,c,c++
    \ set noet sw=4
  autocmd FileType javascript,json,typescript,ruby,css,sass,scss
    \ set et sw=2 ts=2 sts=2
  autocmd FileType vim
    \ set et sw=2 ts=2 sts=2
augroup END

